cleand up cli help menus

diff --git a/libexec/bashlib_print b/libexec/bashlib_print
--- a/libexec/bashlib_print
+++ b/libexec/bashlib_print
@@ -1,12 +1,7 @@
 #!/usr/bin/env bash
-# A CLI tool for the print functions.
+# A CLI tool for print output.
 #
-# This cli program will be a subcommand in the style toolset.
-# should be of the form
-#   print print <codes> <message>
-#   print println <codes> <message>
-#   print print_tag <codes> <tag> <message>
-#   print println_tag <codes> <tag> <message>
+# This subcommand supports a flag-driven interface only.
 
 style_tool_name="style"
 style_cli_print_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
@@ -25,36 +20,38 @@ else
 fi
 
 source "${style_tool_lib_dir}/internal/bashlib_print.bash"
+source "${style_tool_lib_dir}/internal/bashlib_menu.bash"
 
 style_cli_print_usage() {
-    cat <<EOF
-Usage:
-  print <function> [args...]
+    helpmenu_print_title "style print"
+    helpmenu_print_subtitle "Styled output functions"
+    helpmenu_print_header "Usage"
+    printf "  %s\n" "style print [options] <message...>"
 
-Functions:
-  print         <message>
-  print         <codes> <message>
-  println       <message>
-  println       <codes> <message>
-  print_tag     <tag> <message>
-  print_tag     <codes> <tag> <message>
-  println_tag   <tag> <message>
-  println_tag   <codes> <tag> <message>
-  print_error   <message...>
-  print_warn    <message...>
-  print_success <message...>
+    helpmenu_print_header "Options"
+    helpmenu_print_option "-c, --codes <ansi-codes>" "Apply ANSI escape code(s) to message text"
+    helpmenu_print_option "-t, --tag <tag>" "Prefix message with [tag]:"
+    helpmenu_print_option "-n, --newline" "End output with newline"
+    helpmenu_print_option "-e, --error" "Print predefined error message format"
+    helpmenu_print_option "-w, --warn" "Print predefined warning message format"
+    helpmenu_print_option "-s, --success" "Print predefined success message format"
+    helpmenu_print_option "-l, --log" "Print predefined log message format"
+    helpmenu_print_option "-h, --help" "Show this help message"
 
-Examples:
-  print println "hello world"
-  print println "\e[32m" "green text"
-  print print_tag "Info" "starting up"
-  print println_tag "\e[1;34m" "Note" "styled tagged line"
-  print print_error "something failed"
-EOF
+    helpmenu_print_header "Examples"
+    helpmenu_print_example "style" "print --error \"something failed\""
+    helpmenu_print_example "style" "print --warn \"disk usage is high\""
+    helpmenu_print_example "style" "print --success \"done\""
+    helpmenu_print_example "style" "print --codes \"\\e[1;34m\" --tag \"Info\" --newline \"starting up\""
 }
 
 style_cli_print_parse_args() {
-    local func=""
+    local preset=""
+    local codes=""
+    local tag=""
+    local newline=0
+    local message_parts=()
+    local message=""
 
     if [[ "$#" -lt 1 ]]; then
         style_cli_print_usage >&2
@@ -68,37 +65,75 @@ style_cli_print_parse_args() {
             ;;
     esac
 
-    func="$1"
-    shift
+    while [[ "$#" -gt 0 ]]; do
+        case "$1" in
+            -c|--codes)
+                if [[ "$#" -lt 2 ]]; then
+                    print_error "Missing value for $1"
+                    return 1
+                fi
+                codes="$2"
+                shift 2
+                ;;
+            -t|--tag)
+                if [[ "$#" -lt 2 ]]; then
+                    print_error "Missing value for $1"
+                    return 1
+                fi
+                tag="$2"
+                shift 2
+                ;;
+            -n|--newline)
+                newline=1
+                shift
+                ;;
+            -e|--error)
+                preset="error"
+                shift
+                ;;
+            -w|--warn)
+                preset="warn"
+                shift
+                ;;
+            -s|--success)
+                preset="success"
+                shift
+                ;;
+            -l | --log)
+                preset="log"
+                shift
+                ;;
+            -h|--help)
+                style_cli_print_usage
+                return 0
+                ;;
+            --)
+                shift
+                while [[ "$#" -gt 0 ]]; do
+                    message_parts+=("$1")
+                    shift
+                done
+                ;;
+            -*)
+                print_error "Unknown option: $1"
+                style_cli_print_usage >&2
+                return 1
+                ;;
+            *)
+                message_parts+=("$1")
+                shift
+                ;;
+        esac
+    done
 
-    case "$func" in
-        print)
-            print "$@"
-            ;;
-        println)
-            println "$@"
-            ;;
-        print_tag)
-            print_tag "$@"
-            ;;
-        println_tag)
-            println_tag "$@"
-            ;;
-        print_error)
-            print_error "$*"
-            ;;
-        print_warn)
-            print_warn "$*"
-            ;;
-        print_success)
-            print_success "$*"
-            ;;
-        *)
-            print_error "Unknown print function: ${func}"
-            style_cli_print_usage >&2
-            return 1
-            ;;
-    esac
+    message="${message_parts[*]}"
+    if [[ -z "$message" ]]; then
+        print_error "Message is required"
+        style_cli_print_usage >&2
+        return 1
+    fi
+
+    print_with_options "$preset" "$codes" "$tag" "$newline" "$message"
 
     return "$?"
 }
@@ -106,4 +141,4 @@ style_cli_print_parse_args() {
 if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
     style_cli_print_parse_args "$@"
     exit "$?"
-fi
+fi 
diff --git a/style b/style
--- a/style
+++ b/style
@@ -1,135 +1,82 @@
 #!/usr/bin/env bash
-#
-# used to format output.
-# Standard output functions
-#	format error <message>
-#	format warn <message>
-#	format ok <message>
-#	format log <tag> <message>
-#	format logln <tag> <message>
-#
-# Help menu formatting
-#	format title <text>
-#	format header <text>
-#	format option [opts] <flags> <description>
-#	format example <tool> <opts> <args>
+# style subcommand dispatcher.
 
+style_tool_name="style"
+style_script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
+style_libexec_dir=""
+style_lib_dir=""
 
-## Source the required paths.
-SCRIPT_PATH="$(realpath -- "$0")"
-SCRIPT_DIR="$(dirname -- "$SCRIPT_PATH")"
-SCRIPT_NAME="$(basename -- "$0")"
-
-if [[ -d "$SCRIPT_DIR/lib" ]]; then
-    LIB_DIR="$SCRIPT_DIR/lib"
-elif [[ -d "$HOME/.local/lib/$SCRIPT_NAME" ]]; then
-    LIB_DIR="$HOME/.local/lib/$SCRIPT_NAME"
-elif [[ -d "/usr/lib/$SCRIPT_NAME" ]]; then
-    LIB_DIR="/usr/lib/$SCRIPT_NAME"
+if [[ -d "${style_script_dir}/libexec" ]]; then
+    style_libexec_dir="${style_script_dir}/libexec"
+    style_lib_dir="${style_script_dir}/lib"
+elif [[ -d "${HOME}/.local/libexec/${style_tool_name}" ]]; then
+    style_libexec_dir="${HOME}/.local/libexec/${style_tool_name}"
+    style_lib_dir="${HOME}/.local/lib/${style_tool_name}"
+elif [[ -d "/usr/local/libexec/${style_tool_name}" ]]; then
+    style_libexec_dir="/usr/local/libexec/${style_tool_name}"
+    style_lib_dir="/usr/local/lib/${style_tool_name}"
+elif [[ -d "/usr/libexec/${style_tool_name}" ]]; then
+    style_libexec_dir="/usr/libexec/${style_tool_name}"
+    style_lib_dir="/usr/lib/${style_tool_name}"
 else
-    printf '[Error]: Could not locate library directory for %s\n' "$SCRIPT_NAME" >&2
+    printf '\e[1;31m[Error]\e[0m: Unable to locate %s libexec directory.\n' "${style_tool_name}" >&2
     exit 1
 fi
 
-source "$LIB_DIR/help_menu.sh"
-source "$LIB_DIR/format_output.sh"
-## -------------------------
+source "${style_lib_dir}/internal/bashlib_menu.bash"
 
-_format_usage() {
-    cat <<EOF
-Usage:
-  format <command> [args...]
+style_usage() {
+        helpmenu_print_title "style"
+        helpmenu_print_subtitle "A CLI tool for styling different types of output."
+        helpmenu_print_header "Usage"
+        printf "  %s\n" "style <command> [args...]"
 
-Commands:
-  install remove update version
-  error warn ok log logln
-  title header option example
-EOF
+        helpmenu_print_header "Commands"
+        helpmenu_print_option "print" "Styled output functions"
+        helpmenu_print_option "menu" "Help menu formatting functions"
+        helpmenu_print_option "help" "Show this message"
+        helpmenu_print_option "version" "Print version"
+
+        helpmenu_print_header "Examples"
+        helpmenu_print_example "style" "print --error \"something failed\""
+        helpmenu_print_example "style" "print --codes \"\\e[1;36m\" --tag \"Info\" --newline \"booting\""
+        helpmenu_print_example "style" "menu --title \"My Tool\""
+        echo ""
 }
 
-# Makes sure the first arg given is a valid cmd
-_format_valid_cmd() {
-    case "$1" in
-        help|'')
-            _format_usage
-            exit 0
-            ;;
-	version) logln "format" "0.0.1"; exit 0;;
-        install|remove|update|\
-        error|warn|ok|log|logln|\
-        title|header|option|example)
+style_dispatch() {
+    local command="${1:-help}"
+    local command_bin=""
+
+    case "${command}" in
+        help|-h|--help)
+            style_usage
             return 0
             ;;
+        version|-v|--version)
+            printf '%s\n' '0.1.0'
+            return 0
+            ;;
+        print|menu)
+            command_bin="${style_libexec_dir}/bashlib_${command}"
+            ;;
         *)
+            printf '\e[1;31m[Error]\e[0m: Unknown command: %s\n' "${command}" >&2
+            style_usage >&2
             return 1
             ;;
     esac
-}
 
-# _formatter_handle_install <cmd>
-_formatter_handle_install() {
-
-    # Ensure the bash installer is installed to the system
-    which_installer=$(which installer)
-    if [[ -z "$which_installer" ]]; then
-	temp_dir=""
-	installer_repo="https://github.com/JMinyard1335/Bash-Installer"
-	logln "Installer not found on system installing now."
-
-	# create a temp dir
-	temp_dir="$(mktemp -d)" || {
-            error "Failed to create temporary directory"
-            exit 1
-        }
-
-	# attempt to clone
-	git clone "$installer_repo" "$temp_dir" || {
-            error "Failed to clone installer repository"
-            rm -rf -- "$temp_dir"
-            exit 1
-        }
-	
-	"$temp_dir/installer" install "$temp_dir" || {
-            error "Failed to install installer"
-            rm -rf -- "$temp_dir"
-            exit 1
-        }
-
-	rm -rf -- "$temp_dir"
-
-	which_installer="$(command -v installer)"
-        [[ -z "$which_installer" ]] && {
-            error "Installer still not found after installation"
-            exit 1
-        }
+    if [[ ! -x "${command_bin}" ]]; then
+        printf '\e[1;31m[Error]\e[0m: Command executable not found: %s\n' "${command_bin}" >&2
+        return 1
     fi
 
-    case "$cmd" in
-	install) installer install "$SCRIPT_DIR";;
-	update) installer update "$SCRIPT_NAME";;
-	remove) installer remove "$SCRIPT_NAME";;
-    esac
+    shift
+    "${command_bin}" "$@"
 }
 
-# Dispatch to the matching sourced function.
-_formatter_parse_args() {
-    local cmd="${1:-}"
-
-    # make sure command is valid
-    if ! _format_valid_cmd "$cmd"; then
-        error "Invalid command was given"
-        _format_usage
-        exit 1
-    fi
-    shift	# we have the command shift the argument line.
-
-    # if the user wants to run the installer make sure it is on the system first.
-    if [[ "$cmd" == "install" || "$cmd" == "update" || "$cmd" == "remove" ]]; then
-	_formatter_handle_install "$cmd"
-    else
-	"$cmd" "$@"
-    fi
-
-}
-
-_formatter_parse_args "$@"
+if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
+    style_dispatch "$@"
+    exit "$?"
+fi
